# Generated by Django 3.0.7 on 2020-06-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200604_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=64)),
                ('size', models.CharField(choices=[('L', 'L'), ('S', 'S')], max_length=1)),
                ('topping', models.CharField(choices=[('Cheese', 'Cheese'), ('1 item', '1 item'), ('2 items', '2 items'), ('3 items', '3 items'), ('Special', 'Special')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
