# Generated by Django 3.0.7 on 2020-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('1 topping', '1 topping'), ('2 toppings', '2 toppings'), ('3 toppings', '3 toppings'), ('Special', 'Special')], max_length=32),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping1',
            field=models.ManyToManyField(blank=True, related_name='topping1', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping2',
            field=models.ManyToManyField(blank=True, related_name='topping2', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping3',
            field=models.ManyToManyField(blank=True, related_name='topping3', to='orders.Topping'),
        ),
    ]
