# Generated by Django 3.0.7 on 2020-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200605_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping3',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='topping', to='orders.Topping'),
        ),
    ]
