# Generated by Django 3.0.7 on 2020-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200605_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping'),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('1 topping', '1 topping'), ('2 toppings', '2 toppings'), ('3 toppings', '3 toppings'), ('Special', 'Special')], default='L', max_length=32),
            preserve_default=False,
        ),
    ]
