# Generated by Django 3.0.7 on 2020-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200605_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping1',
            field=models.ManyToManyField(blank=True, related_name='topping1', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping2',
            field=models.ManyToManyField(blank=True, related_name='topping2', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping3',
            field=models.ManyToManyField(blank=True, related_name='topping3', to='orders.Topping'),
        ),
    ]
