# Generated by Django 3.0.7 on 2020-06-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200605_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping3',
        ),
    ]
