# Generated by Django 3.0.7 on 2020-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200605_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplate',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.CharField(choices=[('Cheese', 'Cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('Special', 'Special')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('Large', 'Large'), ('Small', 'Small')], max_length=5),
        ),
    ]
