# Generated by Django 3.0.7 on 2020-06-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200605_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExtraSteak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='SubExtra',
            new_name='SubExtraAll',
        ),
        migrations.AddField(
            model_name='sub',
            name='extraSteak',
            field=models.ManyToManyField(blank=True, related_name='extra_steak', to='orders.SubExtraSteak'),
        ),
    ]
