# Generated by Django 3.0.7 on 2020-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200609_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='salad',
            name='hash_name',
            field=models.CharField(default='aaa', max_length=64),
            preserve_default=False,
        ),
    ]
