# Generated by Django 3.0.7 on 2020-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_pasta_hash_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AddField(
            model_name='sub',
            name='hash_name',
            field=models.CharField(default='some', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='priceL',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='priceS',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
