# Generated by Django 3.0.7 on 2020-06-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200613_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='priceL',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='priceS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
