# Generated by Django 3.0.7 on 2020-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200613_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exta',
        ),
        migrations.AddField(
            model_name='order',
            name='extra',
            field=models.CharField(blank=True, default='empty', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_steak',
            field=models.CharField(blank=True, default='empty', max_length=64),
        ),
    ]
