# Generated by Django 3.0.7 on 2020-06-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200613_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='subextraall',
            name='hash_name',
            field=models.CharField(default='empty', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subextrasteak',
            name='hash_name',
            field=models.CharField(default='some', max_length=64),
            preserve_default=False,
        ),
    ]
