# Generated by Django 3.0.7 on 2020-06-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200613_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dinnerplate',
            name='size',
        ),
        migrations.AddField(
            model_name='dinnerplate',
            name='hash_name',
            field=models.CharField(default='some', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerplate',
            name='priceL',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dinnerplate',
            name='priceS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
