# Generated by Django 3.0.7 on 2020-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200615_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra',
            field=models.CharField(default='empty', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_steak',
            field=models.CharField(default='empty', max_length=64),
        ),
    ]
